--- 
projects:
- name: puppet
  remotes:
    origin: git://github.com/puppetlabs/puppet.git
  branches:
  - master
  tags:
  - 0.24.0
  - 0.24.1
  - 0.24.2
  - 0.24.3
  - 0.24.4
  - 0.24.5
  - 0.24.6
  - 0.24.7
  - 0.24.8
  - 0.24.9
  - 0.25.0
  - 0.25.1
  - 0.25.2
  - 0.25.3
  - 0.25.4
  - 0.25.5
  - 0.25.6
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.7
  - 2.6.8
  - 2.6.9
  - 2.6.10
  - 2.6.11
  - 2.6.12
  - 2.6.13
  - 2.7.0
  - 2.7.1
  - 2.7.3
  - 2.7.4
  - 2.7.5
  - 2.7.6
  - 2.7.7
  - 2.7.8
  - 2.7.9
- name: facter
  remotes:
    origin: git://github.com/puppetlabs/facter.git
  branches:
  - master
  tags:
  - 1.0.2
  - 1.1.0
  - 1.1.1
  - 1.1.2
  - 1.1.3
  - 1.1.4
  - 1.2.0
  - 1.2.1
  - 1.3
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - 1.3.5
  - 1.3.6
  - 1.3.7
  - 1.3.8
  - 1.5
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.5.5
  - 1.5.6
  - 1.5.7
  - 1.5.8
  - 1.5.9
  - 1.6.0
  - 1.6.1
  - 1.6.2
  - 1.6.3
  - 1.6.4
- name: enterprise-dist
  remotes:
    origin: git@github.com:puppetlabs/enterprise-dist.git
  branches:
  - master
  tags:
  - 0.1.0
  - 0.1.1
  - 0.2.0
  - 0.3.0
  - 0.4.0
  - 0.5.0
  - 1.0
  - 1.1.0
  - 1.2
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.2.4
  - 2.0.0
- name: stdlib
  remotes:
    origin: git://github.com/puppetlabs/puppetlabs-stdlib.git
  branches:
  - master
  tags:
  - 0.1.1
  - 0.1.2
  - 0.1.3
  - 0.1.4
  - 0.1.5
  - 0.1.6
  - v0.1.7
  - v1.0.0
  - v1.1.0
  - v2.0.0
  - v2.1.0
  - v2.1.1
  - v2.1.2
  - v2.2.0
  - v2.2.1
- name: pe_accounts
  remotes:
    origin: git@github.com:puppetlabs/puppetlabs-pe_accounts.git
  branches:
  - master
  tags:
  - v0.0.1
  - v0.0.2
  - v0.0.3
  - v1.0.0
  - v1.0.1
  - v1.0.2
- name: pe_mcollective
  remotes:
    origin: git@github.com:puppetlabs/puppetlabs-pe_mcollective.git
  branches:
  - master
  tags:
  - v0.0.1
  - v0.0.2
  - v0.0.3
  - v0.0.4
  - v0.0.5
  - v0.0.6
  - v0.0.7
  - v0.0.8
  - v0.0.9
  - v0.0.10
  - v0.0.11
  - v0.0.12
  - v0.0.13
  - v0.0.14
  - v0.0.15
  - v0.0.16
  - v0.0.17
  - v0.0.18
  - v0.0.23
  - v0.0.24
  - v0.0.25
  - v0.0.26
  - v0.0.27
  - v0.0.28
  - v0.0.29
  - v0.0.32
  - v0.0.34
  - v0.0.35
  - v0.0.36
  - 0.0.38
- name: pe_compliance
  remotes:
    origin: git@github.com:puppetlabs/puppetlabs-pe_compliance.git
  branches:
  - master
  tags:
  - v0.0.1
  - v0.0.2
  - v0.0.3
  - v0.0.4
- name: puppet-dashboard
  remotes:
    origin: git://github.com/puppetlabs/puppet-dashboard.git
  branches:
  - master
  tags:
  - v0.0.1
  - v0.0.2
  - v0.1.0
  - v0.1.1
  - v0.2.0
  - v0.2.1
  - v1.0.0
  - v1.0.1
  - v1.0.2
  - v1.0.3
  - v1.0.4
  - v1.1.0
  - v1.1.1
  - v1.1.9
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.2.4
- name: dashboard-module-baseline
  remotes:
    origin: git@github.com:puppetlabs/dashboard-module-baseline.git
  branches:
  - master
  tags:
  - 0.0.0
  - 0.1.0
  - 1.2
  - 1.2.0
  - 2.0.1
- name: cloud-provisioner
  remotes:
    origin: git://github.com/puppetlabs/puppetlabs-cloud-provisioner.git
  branches:
  - master
  tags:
  - v0.0.1
  - v1.0.0
  - v1.0.1
- name: cloud-provisioner-vmware
  remotes:
    origin: git@github.com:puppetlabs/puppetlabs-cloud-provisioner-vmware.git
  branches:
  - master
  tags:
  - v0.0.1
  - v1.0.0
- name: live-management
  remotes:
    origin: git@github.com:puppetlabs/live-management.git
  branches:
  - master
  tags:
  - v0.0.01
  - v0.0.02
  - v0.0.03
  - v0.0.04
  - v0.0.05
  - v0.0.06
  - 0.0.07
  - 0.0.08
  - 0.0.09
  - 0.0.11
  - 0.0.12
  - 0.0.13
  - 0.0.14
  - v0.0.15
  - 0.0.16
  - 0.0.17
  - 0.0.18
  - 0.0.19
  - 1.0.0
- name: mcollective
  remotes:
    origin: git://github.com/puppetlabs/marionette-collective.git
  branches:
  - master
  tags:
  - 0.2.0
  - 0.3.0
  - 0.4.0
  - 0.4.1
  - 0.4.2
  - 0.4.3
  - 0.4.4
  - 0.4.5
  - 0.4.6
  - 0.4.7
  - 0.4.8
  - 0.4.9
  - 0.4.10
  - 1.0.0
  - 1.0.1
  - 1.1.0
  - 1.1.1
  - 1.1.2
  - 1.1.3
  - 1.1.4
  - 1.2.0
  - 1.2.1
  - 1.3.0
  - 1.3.1
  - 1.3.2
- name: mcollective-plugins
  remotes:
    origin: git://github.com/puppetlabs/mcollective-plugins.git
  branches:
  - master
  tags:
  - pe1.2
